# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    providers:
        user:
            id: app.user_provider

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern: ^/admin.*$
            anonymous: ~
            provider: user
            simple_form:
                authenticator: app.admin_authenticator
                login_path: admin_auth_login
                check_path: admin_auth_login_check
                default_target_path: /admin
                username_parameter: login[username]
                password_parameter: login[password]
            logout:
                path: admin_auth_logout
                target: /admin/login
            context: app

        user:
            pattern: ^/.*$
            anonymous: ~
            provider: user
            simple_form:
                authenticator: app.user_authenticator
                login_path: app_auth_login
                check_path: app_auth_login_check
                default_target_path: homepage
                username_parameter: login[username]
                password_parameter: login[password]
            logout:
                path: app_auth_logout
                target: /login
            context: app


            # access_control:
